version: '3.8'

services:
  # Streamlit UI servisi
  streamlit:
    build:
      context: .
      dockerfile: Dockerfile
    command: python run_streamlit.py
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
      - ./models:/app/models
      - ./pdf:/app/pdf
    ports:
      - "8501:8501"
    environment:
      - PYTHONUNBUFFERED=1
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8501"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

  # FastAPI servisi
  api:
    build:
      context: .
      dockerfile: Dockerfile
    command: python run_api.py
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
      - ./models:/app/models
      - ./pdf:/app/pdf
    ports:
      - "8000:8000"
    environment:
      - PYTHONUNBUFFERED=1
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/api/v1/status"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

  # Nginx proxy (opsiyonel)
  # nginx:
  #   image: nginx:latest
  #   volumes:
  #     - ./nginx/nginx.conf:/etc/nginx/nginx.conf
  #   ports:
  #     - "80:80"
  #   depends_on:
  #     - streamlit
  #     - api
  #   restart: unless-stopped 