# Development Configuration
debug: true
log_level: DEBUG
vector_db_path: ./data/vector_db
model_path: ./models
cache_enabled: true
cache_ttl: 300

# Model settings
llm:
  temperature: 0.1
  max_tokens: 512
  context_length: 2048

# Vector store settings
vector_store:
  top_k: 3
  embedding_model: "sentence-transformers/all-MiniLM-L6-v2"
